development:
  adapter: async
  database: ajax_app_development

test:
  adapter: test
  database: ajax_app_test

production:
  database: ajax_app_production
  username: ajax_app
  password: <%= ENV['FIRST_APP_DATABASE_PASSWORD'] %>